sample/furniture/common/urls.py
from django.urls import path
from .import views
app_name = 'common'
urlpatterns=[
     path('home',views.home, name="home"),
     path('cust_reg',views.cust_reg, name="cust_reg"),
     path('seller_reg',views.seller_reg, name="seller_reg"),
     path('cust_login',views.cust_login, name="cust_login"),
     path('seller_login',views.seller_login, name="seller_login"),
     path('seller_forgot',views.seller_forgot, name="seller_forgot"),
     path('cust_forgot',views.cust_forgot, name="cust_forgot"),
     path('prod_list/<int:id>',views.prod_list, name="prod_list"),
     path('about',views.abuot, name="about"),

]

sample/furniture/furniture/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('customer/', include('customer.urls')),
    path('seller/', include('seller.urls'))
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sample/furniture/seller/urls.py
from django.urls import path
from .import views
app_name = 'seller'
urlpatterns=[
     path('home',views.home, name="home"),
     path('help',views.help, name="help"),
     path('about',views.about, name="about"),
     path('master',views.master, name="master"),
     path('add_product',views.add_product, name="add_product"),
     path('stock/<int:stock_id>/update/', views.update_stock, name='update_stock'),
     path('get_data',views.get_data, name="get_data"),
     path('seller_logout',views.seller_logout, name='seller_logout'),
     path('account',views.account, name="account"),
     path('success',views.success, name="success"),

     # path('view_orders',views.view_orders, name="view_orders"),
]     

sample/furniture/seller/models.py
from django.db import models
from ecom_admin.models import Category



# Create your models here.
class Product(models.Model):
    pro_name=models.CharField(max_length=100)
    pro_number=models.CharField(max_length=300)
    pro_category=models.ForeignKey(Category,on_delete=models.CASCADE,default='')
    pro_description=models.CharField(max_length=400)
    pro_price=models.BigIntegerField()
    pro_quantity=models.BigIntegerField()
    
    pro_image=models.ImageField(upload_to='seller/')

    class Meta:
        db_table = 'product'

sample/furniture/seller/views.py
from random import sample
from django.shortcuts import redirect, render
from common.models import Customer, Seller
from ecom_admin.models import Category
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.db.models.functions import Random

from django.shortcuts import get_object_or_404, render

from seller.models import Product

# Create your views here.
def home(request):
    seller=Seller.objects.get(id=request.session['Seller'])
    product = Product.objects.filter(id=request.session['Seller']).values('pro_name','pro_image','pro_price')
    
    context = {
        'data' : product,
        'user':seller,
    }
    return render(request, 'seller/home.html',context)
#

def master(request):
    seller=Seller.objects.get(id=request.session['Seller'])
    return render(request, 'seller/master.html',{'user':seller})



def add_product(request):
    seller=Seller.objects.get(id=request.session['Seller'])
    all_category=Category.objects.all()
    if request.method == 'POST':
        product_name=request.POST['p_name']
        product_number=request.POST['p_number']
        product_category=request.POST['p_category']
        product_description=request.POST['p_description']
        product_price=request.POST['p_price']
        product_quantity=request.POST['p_quantity']
        product_image=request.FILES['p_image']
        print(product_category)
        new_product = Product(
            pro_name=product_name,
            pro_number=product_number,
            pro_category_id=product_category,
            pro_description=product_description,
            pro_price=product_price,
            pro_quantity=product_quantity,
            pro_image=product_image
        )
        new_product.save()
  
        

    return render(request, 'seller/add_product.html',{'data':all_category,'user':seller})

# def update_stock(request):
#     seller=Seller.objects.get(id=request.session['Seller'])
#     all_cate=Category.objects.all()
#     context = {
#         'user' : seller,
#         'data':all_cate
#     }
    
#     return render(request, 'seller/update_stock.html',context)
# # views.py


def update_stock(request, stock_id):
    stock = get_object_or_404(Product, id=stock_id)

    if request.method == 'POST':
        # Retrieve the updated data from the form
        quantity = request.POST['quantity']
        price = request.POST['price']

        # Update the stock object
        stock.pro_quantity = quantity
        stock.pro_price = price

        # Save the changes
        stock .save()

        # Redirect to a success page or do something else
        return render(request, 'success.html')

    return render(request, 'update_stock.html', {'stock':stock})








# def view_orders(request):
#     customer=Customer.objects.all()
#     product=Product.objects.get()
#     cart=Cart.objects.get

#     return render(request, 'seller/view_orders.html')

def help(request):
    seller=Seller.objects.get(id=request.session['Seller'])
    return render(request, 'seller/help.html',{'user':seller})

def success(request):
    return render(request, 'seller/success.html')

def about(request):
    seller=Seller.objects.get(id=request.session['Seller'])
    return render(request, 'seller/about.html',{'user':seller})



def account(request):
    seller=Seller.objects.get(id=request.session['Seller'])
    if request.method == 'POST':
        up_name = request.POST['ed_name']
        up_phone = request.POST['ed_phone']
        up_email = request.POST['ed_email']
        up_gender = request.POST['ed_gender']
        up_address = request.POST['ed_address']

        edit_seller = Seller.objects.filter(id=request.session['Seller'])

        if (up_name != ''):
            edit_seller.update(name=up_name)
        else:
            print('else')
        if (up_phone != ''):
            edit_seller.update(phone=up_phone)
        else:
            print('else')
       
        if (up_email != ''):
            edit_seller.update(e_mail=up_email)
        else:
            print('else')
        if (up_gender != ''):
            edit_seller.update(gender=up_gender)
        else:
            print('else')
        if (up_address != ''):
            edit_seller.update(address=up_address)
        else:
            print('else')
        try:
            up_image = request.FILES['ed_image']
            seller.image = up_image
            seller.save()
        except:
            up_image = None
    return render(request, 'seller/account.html',{'user':seller})


def seller_logout(request):
    del request.session['Seller']
    request.session.flush()
    return redirect('common:home')


@csrf_exempt
def get_data(request):
    # if request.method == 'POST':
        print("Reached inside request")

        selected_option = request.POST['option']
        print("select",selected_option)
        data = Product.objects.filter(pro_category=selected_option)
        print("ffff",data)
        data1=[ {"id":i.id,"pro_name":i.pro_name,"pro_quantity":i.pro_quantity}for i in data]
        return JsonResponse({'pro_data': data1})
    # else:
    #     return JsonResponse({'pro_data' : 'null'})

sample/furniture/seller/templates/seller/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <style>
        *{
            padding: 0;
            margin: 0;
        }
       
       a {
            text-decoration: none;
        }

        nav {


            display: flex;
            position: sticky;
            top: 0;
            z-index: 2;
            width: 100%;
            height: 80px;
            color: #fff;
            box-shadow: 2px 2px 5px #888888;
            background-color: lightblue;
        }

        nav ul {
            margin: 0;
            padding: 0;
            list-style: none;
            display: flex;
            margin-top: 20px;
            font-family: 'Kaushan Script', cursive;
            font-family: 'Libre Baskerville', serif;
            font-family: 'Poppins', sans-serif;
            /* justify-content: space-between; */
        }

        nav li {
            padding: 1rem;
            list-style: none;

        }

        nav a {
            color: white;
            text-decoration: none;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 19px;
            font-weight: 100px;
        }

        nav a:hover {
            color: #111110;
        }

        nav img {
            width: 20px;
            height: 30px;
        }

        input {
            margin-left: 80px;
            width: 400px;
            height: 40px;
            margin-top: 20px;

            border-radius: 8px;

        }

        .left {
            background-color: transparent;
            width: 35%;
            display: flex;
            justify-content: center;
            font-family: Arial, Helvetica, sans-serif;
            align-items: center;
            color: black;


        }

        #icon {
            width: 50px;
            height: 50px;
        }

        .left ul {
            margin-top: 7px;
            /* margin-left: 60px; */
            color: black;
        }

        .center {
            display: flex;
            background-color: transparent;
            width: 35%;

        }

        #input {
            margin-right: 50px;
        }

        .right {
            background-color: transparent;
            color: black;
            width: 30%;
            display: flex;
            flex-direction: row;
            justify-content: space-around;
            align-items: center;
            font-family: Arial, Helvetica, sans-serif;
        }

        .right button {

            width: 80px;
            border-radius: 7px;
            height: 30px;
            font-size: 13px;
            background-color: rgb(29, 28, 28);
            color: white;
        }

        .right #profile img {
            /* background-color: #f1c40f; */
            border-radius: 50px;
            width: 50px;
            height: 50px;
        }


        /* ////////////////////////////////content starting \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
        .container {
            /* background-color: rgb(101, 173, 101); */
            width: 90%;
            height: 500px;
            display: flex;
            margin-left: 65px;
            margin-top: 30px;
        }

        .left_about {
            /* background-color: lightcoral; */
            width: 20%;
            border-radius: 0% 100% 0% 100% / 100% 56% 44% 0%;
        }

        .left_about h3 {
            font-family: Arial, Helvetica, sans-serif;
            margin-top: 130%;
            margin-left: 25px;
            font-size: 35px;
        }

        .left_about p {
            padding-left: 20px;
            font-size: 24px;
            font-family: Arial, Helvetica, sans-serif;

        }

        .right_about {
            width: 90%;
            background-color: rgb(224, 224, 46);
            background: url("/static/images/about8.jpg");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            border-radius: 0% 100% 0% 100% / 43% 0% 100% 57%;
            border-bottom-right-radius: 8px;
            border-top-right-radius: 8px;
        }

        .container2 {
            /* background-color: rgb(157, 162, 194); */
            width: 90%;
            height: 400px;
            /* display: flex; */
            margin-left: 65px;
        }

        .container2 p {
            padding-left: 20px;
            font-size: 19px;
            font-family: Arial, Helvetica, sans-serif;

        }

        #p1 {
            font-size: 19px;
            margin-left: 370px;
        }

        #p2 {
            font-size: 19px;
            margin-left: 250px;
        }

        #p3 {
            font-size: 22px;
            margin-left: 40px;
        }
    </style>
</head>

<body>
    <nav>

        <div class="left">
            <div class="left_sub">
                <a href="http://127.0.0.1:8000/seller/home">
                    <h2 style="margin-right: 100px;">ΞLIΓΞ</h2>
                </a>
            </div>
            <div class="left_sub">
                <ul>
                    <li><a href="http://127.0.0.1:8000/seller/add_product"> <span class="material-symbols-outlined">
                        add_box
                        </span></a></li>
                    <li><a href="http://127.0.0.1:8000/seller/update_stock"><span class="material-symbols-outlined">
                        sync_alt
                        </span></a></li>
                     <li><a href="http://127.0.0.1:8000/seller/view_orders"> <span class="material-symbols-outlined">
                        visibility
                        </span></a></li>
                    
                </ul>
            </div>
        </div>
        <div class="center">
            <input type="search" id="input" placeholder="Search......">
        </div>
        <div class="right">
                <li><a href="http://127.0.0.1:8000/seller/help"><span class="material-symbols-outlined">
                    support_agent
                    </span></a></li>
                <li><a href=""><span class="material-symbols-outlined">notifications_active</span></a></li>

            <div class="box"><a href="{% url 'seller:seller_logout' %}"><span class="material-symbols-outlined">
                Logout
                </span></a></div>
            <div id="profile">
                <a href="{% url 'seller:account' %}"><img src="{{user.image.url}}"></a>
            </div>
        </div>
    </nav>




    <div class="container">
        <div class="left_about">
            <p style="margin-left: 20px; margin-top: 20px; font-size: 25px;">ΞLIΓΞ</p>
            <h3>About Us</h3>
            <hr>
            <p><b> Welcome to Elite...!</b></p>
        </div>
        <div class="right_about"></div>

    </div>
    <div class="container2">
        <p id="p1"> Finally your go-to destination for stylish and affordable furniture.</p>
        <p> We're a family-owned business founded by a team of passionate designers and furniture experts who believe
            that everyone should have access to beautiful,<br> high-quality furnishings.

            Our mission is simple: to provide our customers with a curated selection of furniture that meets their
            unique needs and preferences.<br>Whether you're furnishing a cozy apartment or a spacious home, we have a
            wide range of styles and designs to choose from, including mid-century modern,<br> contemporary, and rustic.

            At Elite, we're committed to providing exceptional customer service.<br>
        <p id="p2"> Our team is dedicated to helping you find the perfect furniture pieces for your home, and we're
            always available</p>
        <p> to answer any questions you may have. Plus, with fast and reliable shipping, easy returns, and a hassle-free
            checkout process, shopping with us is a breeze.

            We're passionate about design and believe that furniture should be both beautiful and functional. That's why
            we carefully curate our selection <br>to ensure that every piece we offer meets our high standards for
            quality and style.<br>

            <b> Thank you for choosing Elite as your trusted source for furniture. We look forward to helping you create
                the home of your dreams.</b>
        </p>
        <h2 style="text-align: center; font-family: Arial, Helvetica, sans-serif;">Vist Again</h2>
        <h3 style="text-align: center; word-spacing: 8px; font-family: Arial, Helvetica, sans-serif;">Love From ELITE
            GROUP</h3>
    </div>
</body>

</html>

sample/furniture/seller/templates/seller/account.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/seller_account.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

</head>
<body>
    <!-- //////////nav starting\\\\\\\\\\\\\\\ -->

    <nav>

        <div class="left_nav">
            <div class="left_sub">
                <a href="http://127.0.0.1:8000/seller/home"><h2 style="margin-right: 50px;">ΞLIΓΞ</h2></a>
            </div>
            <div class="left_sub">
                <ul>
                    <li><a href="#">About</a></li>
                    <li><a href="http://127.0.0.1:8000/seller/help"><span class="material-symbols-outlined">
                        Phone_In_Talk
                        </span></a></li>
                </ul>
            </div>
        </div>
        <div class="center">
            <input type="search" id="inputt" placeholder="Search......">
        </div>
        <div class="right_nav">
            <div class="box"><a href="{% url 'seller:seller_logout' %}"><span class="material-symbols-outlined">
                Logout
                </span></a></div>
            <!-- <div class="box"><a href="http://127.0.0.1:8000/customer/cart"><span class="material-symbols-outlined">
                shopping_cart_checkout
                </span></a></div> -->
            <div id="profile">
               <a href="{% url 'seller:account' %}"><img src="{{user.image.url}}" ></a> 
            </div>
        </div>
    </nav>

    <!-- //////////nav ending\\\\\\\\\\\\\\\ -->

    <div  class="links">
        <button id="update" type="submit">UPDATE</button>

    </div>
    
    <div class="container">
        <div class="sub">

            <div class="left">
                <div class="image">
                    <img id="imgg" src="{{user.image.url}}" alt="">
                </div>
            </div>
            <div class="right">
                <table>
                    <thead>
                        <tr>
                            <td>
                                <h1><i>{{user.name}}</i></h1><br>
                            </td>
                           
                        </tr>
                        <tr>
                            <td>
                                <h3><i>{{user.gender}}</i></h3>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h3><i>{{user.phone}}</i></h3>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h3><i>{{user.e_mail}}</i></h3>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h3><i>{{user.address}}</i></h3>
                            </td>
                        </tr>
                    </thead>
                </table>
            </div>
            <div id="update_div">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h2 style="text-align: center; color: #fff;">EDIT YOUR DETAILS</h2>
                    <br>
                    <input type="text" name="ed_name" placeholder=" Name">
                    <input type="mail" name="ed_email" placeholder="E-mail">
                    <select name="ed_gender" id="">
                        <option value="">gender</option>
                        <option value="male">male</option>
                        <option value="female">female</option>
                    </select>
                    <input type="number" name="ed_phone" placeholder="Mobile" min="0"><br><br><br>
                    <input type="Addreas" name="ed_address" placeholder="Address">
                    <input type="file" id="pro_img" name="ed_image"><br><br>
                    <button type="submit" id="sub_btn">SUBMIT</button>
                    <button type="submit" id="sub_btn2">CLOSE</button>

                </form>
            </div>

        </div>
    </div>

    <!-- ////////footer starting ////////////-->
    <div class="contanier_footer">
        <div class="container_sub">
            <div class="div_1">
                <h3>TOP CATEGORIES</h3>
                <li><a href="">Table</a> </li>
                <li><a href="">Chair</a></li>
                <li><a href="">Sofa</a></li>
                <li><a href="">Bed</a></li>
            </div>
            <div class="div_2">
                <h3>HELP</h3>
                <li><a href="">Delivery</a></li>
                <li><a href="">Returns</a></li>
                <li><a href="">Track an order</a></li>
                <li><a href="">Contact us</a></li>
            </div>
            <div class="div_3">
                <h3>ABOUT US</h3>
                <li><a href="">Careers</a></li>
                <li><a href="">Terms & Conditios</a></li>
                <li><a href="">Privacy Policy</a></li>
                <li><a href="">Responsibility</a></li>
            </div>
            <div class="div_4">
                <h3>FEEDBACK</h3>
                <li>Leave a feedback</li>
                <input type="text" placeholder="Type something.....">
            </div>
        </div>
        <div class="container_sub2">
            <div class="d1">
                <h4>FIND A STORE</h4>
                <button type="submit">STORE LOCATOR</button>
            </div>
            <div class="d2">
                <h5>FOLLOW US</h5>
                <img src="{% static 'images/mainlogs (3).png' %}">
                <img src="{% static 'images/mainlogs (2).png' %}">
                <img src="{% static 'images/mainlogs (1).png' %}">
                <img src="{% static 'images/youtube.png' %}">
            </div>
            <div class="d3">
                <h5>NEWS LETTER SUBSCRIPTION</h5>
                <p>Receive product news and upadtes in your mail</p>
                <input type="text" placeholder="Enter your mail">
            </div>
        </div>
    </div>
    <!-- ////////footer ending ////////////-->

    <script>
        $(document).ready(function () {
            $('#update').click(function () {
                $('#update_div').css('display', 'block');
            })

            $('#sub_btn2').click(function () {
                $('#update_div').css('display', 'none');
            })
        })
    </script>
</body>
</html>

sample/furniture/seller/templates/seller/add_product.html
{% extends "seller/master.html" %}
{% load static %}
{% block title %}help{% endblock %}
{% block head %}    <link rel="stylesheet" href="{% static 'css/add_produt.css' %}">{% endblock %}
   
  {% block body %}
    
  


    <h1 style="color: #fff; font-family: Arial, Helvetica, sans-serif;">Add Product</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="">Product Name</label>
        <input type="text" id="name" name="p_name" required>
        <label  style="margin-left: 70px;">Product No<span style="margin-left: 170px;">Category</span> </label>
        <input type="number" id="pro_number" name="p_number" placeholder="Product No" min="0">
        <select name="p_category" id="pro_cat">
            <option value="">category</option>
            {% for i in data %}
            <option value="{{i.id}}">{{i.category_name}}</option>
            {% endfor %}
        </select>
        <label for=""  >Product Description</label>
        <textarea id="description" name="p_description" rows="8" required></textarea>
        <label  style="margin-left: 70px;">Price<span style="margin-left: 220px;">Quantity</span> </label>
        <input type="number" id="price" name="p_price" min="0" placeholder="Price" required>
        <input type="number" id="quantity" name="p_quantity" min="0" placeholder="Quantity" required>
        <label style="margin-left: 150px;">Image</label>
        <input type="file" id="image" name="p_image" required>
        <button type="submit"  id="add_prod" > add Product</button>
    </form>
{% endblock %}

sample/furniture/seller/templates/seller/help.html
{% extends "seller/master.html" %}
{% load static %}
{% block title %}help{% endblock %}
{% block head %}<link rel="stylesheet" href="{% static 'css/seller_help.css' %}">{% endblock %}
   
  {% block body %}
    
    <div class="container">
        <div class="sub">
            <form action="">
        <h2 id="h2">please write your opinion</h2>

                <textarea name="" id="" cols="60" rows="15"></textarea><br>
                <input type="mail" id="inp" placeholder="Enter your mail" required >
                <button type="submit" >submit</button>
            </form>
        </div>
    </div>
{% endblock %}

sample/furniture/seller/templates/seller/home.html
{% extends "seller/master.html" %}
{% load static %}
{% block title %}home{% endblock %}
{% block head %}<link rel="stylesheet" href="{% static 'css/seller_home.css' %}">{% endblock %}
   
  {% block body %}
  <div class="products">
    {% for i in data %}
    <div class="items" >
      <div class="sub" >
        <a href=""><img  id="pro_img" src="{{i.pro_image.url}}" ></a>
         <b>{{i.pro_name}}</b><br>
        <span style="color: rgb(233, 113, 113);"><b>PRICE:</b> <b>{{i.pro_price}}</b> </span><br>
        <span><b>Rating:</b></span> 
       </div>
    </div>
      
      {% endfor %}
   </div>
    {% endblock %}

sample/furniture/seller/templates/seller/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    gt
</body>
</html>

sample/furniture/seller/templates/seller/update_stock.html
{% extends "seller/master.html" %}
{% load static %}
{% block title %}home{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/update_stock.css' %}">{% endblock %}

{% block body %}

<!-- <div class="container">
    <div class="items">
        <select name="" id="cat">
            <option value="">category</option>
            {% for i in data %}
            <option value="{{i.id}}">{{i.category_name}}</option>
            {% endfor %}
        </select>
        <select name="" id="pro_cate">

        </select>
        <input type="number" id="inp" placeholder="Quantity" min="1">
        <button type="submit">update product</button>
    </div>
</div> -->

<!-- <script>

    $('#cat').change(function () {
        category = $('#cat').val()
        console.log(category)
        console.log('Selected')
        $.ajax({
            url: "http://127.0.0.1:8000/seller/get_data",
            method: "POST",
            data: { 'option': category },
            success: function (response) {
                console.log(response.pro_data)
                hh = ""
                for (item in response.pro_data) {
                    hh += `
                             <option value="${item.id}">${item.pro_name}</option>
                    
                            `
                }



            }
        });
    })
    $('#cat').change(function () {
    category = $('#cat').val()
    console.log(category)
    console.log(category)
    $.ajax({
        url: "http://127.0.0.1:8000/seller/get_data",
        method: "POST",
        data: { 'option': category },
        success: function (response) {
            console.log(response.pro_data)
            var pro_id = $('#pro').val();
            var stock = $('#stock').val();
            $.ajax({
                url: "http://127.0.0.1:8000/seller/update_stock",
                method: "POST",
                data: { 'pro_id': pro_id, 'stock': stock },
                success: function (response) {
                    console.log(response);
                    // Handle the response from the stock update API
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log(textStatus, errorThrown);
                    // Handle the error
                }
            });
        },
        error: function (jqXHR, textStatus, errorThrown) {
            console.log(textStatus, errorThrown);
            // Handle the error
        }
    });
});




</script> -->
<!-- update_stock.html -->
<form method="POST" action="{% url 'update_stock' Product.id %}">
    {% csrf_token %}
    <label for="quantity">Quantity:</label>
    <input type="number" name="quantity" value="{{ Product.pro_quantity }}">
    <br>
    <label for="price">Price:</label>
    <input type="text" name="price" value="{{ Product.pro_price }}">
    <br>
    <input type="submit" value="Update">
</form>


{% endblock %}

sample/furniture/seller/templates/seller/view_orders.html
<!-- {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>view orderes</title>
    <link rel="stylesheet" href="{% static 'css/view_orders.css' %}">
    <style>

    </style>
</head>

<body>
    <div class="text_space">
        <h2>ORDERS LIST</h2>
    </div>

    <div class="table_cover">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">SI NO </th>
                    <th scope="col">ORD DATE</th>
                    <th scope="col">PRD ID</th>
                    <th scope="col">PRD NAME</th>
                    <th scope="col">CUST NAME</th>
                    <th scope="col">CUST MOBAIL</th>
                    <th scope="col">SHIPPING ADDRESS</th>
                    <th scope="col">PRD QTY</th>
                    <th scope="col">TOTAL PRICE</th>
                </tr>
            </thead>
            <tbody>
                {% for order in customer %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{}}</td>
                    <td>{{order.id}}</td>
                    <td>{{order.pro_name}}</td>
                    <td>{{order.name}}</td>
                    <td>{{order.phone}}</td>
                    <td>{{}}</td>
                    <td>{{order.quantity}}</td>
                    <td>{{order.pro_price}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="text_space">
        <a href="seller_home"><button class="btn_add">home</button></a>
    </div>
</body>

</html> -->