sample/furniture/common/urls.py
from django.urls import path
from .import views
app_name = 'common'
urlpatterns=[
     path('home',views.home, name="home"),
     path('cust_reg',views.cust_reg, name="cust_reg"),
     path('seller_reg',views.seller_reg, name="seller_reg"),
     path('cust_login',views.cust_login, name="cust_login"),
     path('seller_login',views.seller_login, name="seller_login"),
     path('seller_forgot',views.seller_forgot, name="seller_forgot"),
     path('cust_forgot',views.cust_forgot, name="cust_forgot"),
     path('prod_list/<int:id>',views.prod_list, name="prod_list"),
     path('about',views.abuot, name="about"),

]

sample/furniture/customer/urls.py
from django.urls import path
from .import views
app_name = 'customer'
urlpatterns=[
     path('home',views.home, name="home"),
     path('help',views.help, name="help"),
     path('cart',views.cart, name="cart"),
     path('product_dtls/<int:id>',views.product_dtls, name="product_dtls"),
     path('product/<int:id>',views.product, name="product"),
     path('master',views.master, name="master"),
     path('myorders',views.myorders, name="myorders"),
     path('remove/<int:id>', views.remove, name='remove'),
     path('cust_logout',views.cust_logout, name='cust_logout'),
     path('account',views.account, name='account'),
     path('about',views.about, name='about'),
     path('checkout',views.checkout, name='checkout'),
     path('payment',views.payment, name='payment'),
     path('result',views.result, name='result'),


]     

sample/furniture/furniture/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('customer/', include('customer.urls')),
    path('seller/', include('seller.urls'))
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sample/furniture/common/models.py
from django.db import models

# Create your models here.
class Seller(models.Model):
    name=models.CharField(max_length=50)
    company_name=models.CharField(max_length=100)
    gender=models.CharField(max_length=50)
    bank_name=models.CharField(max_length=100)
    e_mail=models.CharField(max_length=50)
    company_address=models.CharField(max_length=100)
    phone=models.BigIntegerField()
    acc_holder=models.CharField(max_length=50)
    address=models.CharField(max_length=100)
    accNo=models.BigIntegerField()
    image = models.ImageField(upload_to='seller/')
    ifsc=models.CharField(max_length=50)
    username=models.CharField(max_length=100,default='')
    password=models.CharField(max_length=100,default='')
    status=models.CharField(max_length=30, default='pending..')
     
    class Meta:
        db_table='seller'

class Customer(models.Model):
    name=models.CharField(max_length=50)
    gender=models.CharField(max_length=50,default='')
    phone=models.BigIntegerField()
    address=models.CharField(max_length=200,default='')
    e_mail=models.CharField(max_length=100)
    password=models.CharField(max_length=100)
    cnfm_password=models.CharField(max_length=100)
    image=models.ImageField(upload_to='customer/',default='')


    class Meta:
        db_table='customer'

       




    

sample/furniture/common/views.py
from django.db.models.functions import Random
from random import sample
from django.conf import settings
from django.shortcuts import redirect, render
from common.decorators import auth_customer

from common.models import Customer, Seller
from django.core.mail import send_mail
from django.conf import settings
from customer.models import CustomCart

from seller.models import Product

# Create your views here.
def home(request):
    all_product = Product.objects.order_by(Random())
    setlimit = sample(list(all_product),8)

    context = {
        'data' : setlimit
        

    }
    return render(request, 'common/home.html',context)
# @auth_customer
def prod_list(request,id):
    view_product=Product.objects.get(id=id)

    if request.method == 'POST':
        prod_id=Product.objects.get(id=id)
        cust_id=Customer.objects.get(id = request.session['Customer'])
        qty=request.POST['qty']
        
        add_cart = CustomCart(
            product=prod_id,
            customer=cust_id,
            quantity=qty
        )
        add_cart.save()

    return render(request, 'common/prod_list.html',{'data':view_product})

def abuot(request):
    return render(request, 'common/about.html')
def cust_login(request):
    msg = ''
    if request.method =='POST':
        customer_mail=request.POST['c_mail']
        customer_pass=request.POST['c_pass']
        try:
            find_customer = Customer.objects.get(e_mail=customer_mail,password=customer_pass)
            request.session['Customer'] = find_customer.id
            return redirect('customer:home')
        except:
            msg = 'E-mail or Password Invalid'

    return render(request, 'common/cust_login.html',{'msg':msg})

def cust_reg(request):
    if request.method == "POST":
        cust_name=request.POST['c_name']
        cust_geder=request.POST['c_gender']
        phone=request.POST['c_number']
        cust_address=request.POST['c_address']
        cust_mail=request.POST['c_mail']
        cust_password=request.POST['c_pass']
        cust_cnfm_pass=request.POST['c_confirm pass']
        cust_img=request.FILES['c_image']


        new_customer = Customer(
            name=cust_name,
            gender=cust_geder,
            phone=phone,
            address=cust_address,
            e_mail=cust_mail,
            password=cust_password,
            cnfm_password=cust_cnfm_pass,
            image=cust_img

        )

        new_customer.save()
     
    return render(request, 'common/cust_reg.html')

def seller_login(request):
    msg=''
    if request.method == 'POST':
        seller_username= request.POST['seller_name']
        seller_password= request.POST['seller_pass']
        try:
            find_seller = Seller.objects.get(username=seller_username,password=seller_password)
            request.session['Seller'] = find_seller.id
            return redirect('seller:home')
        except:
            msg = 'username or password is not invalid'
            
    
    return render(request, 'common/seller_login.html',{'msg':msg})

def seller_reg(request):
    if request.method == 'POST':
        seller_name = request.POST['s_name']
        seller_company_name = request.POST['s_company name']
        seller_gender = request.POST['s_gender']
        seller_bank_name = request.POST['s_bank_name']
        seller_eamil = request.POST['s_email']
        seller_cmpny_address = request.POST['s_company_address']
        seller_number = request.POST['s_num']
        seller_acc_holder_name = request.POST['s_account_holder_name']
        seller_address = request.POST['s_address']
        seller_ac_nubmer = request.POST['s_ac_number']
        seller_image = request.FILES['s_image']
        seller_ifsc =request.POST['s_ifsc']

        new_seller = Seller(
            name=seller_name,
            company_name=seller_company_name,
            gender = seller_gender,
            bank_name = seller_bank_name,
            e_mail = seller_eamil,
            company_address = seller_cmpny_address,
            phone = seller_number,
            acc_holder = seller_acc_holder_name,
            address = seller_address,
            accNo = seller_ac_nubmer,
            image = seller_image,
            ifsc =seller_ifsc
        )
        new_seller.save()

    return render(request, 'common/seller_reg.html')



def seller_forgot(request):
     msg =''
     if request.method=='POST':
        entered_email = request.POST['forget_mail']
        try:
            check=Seller.objects.get(e_mail = entered_email)
            password=check.password
            send_mail(
                'your password is',
                password,
                settings.EMAIL_HOST_USER,
                [entered_email],
                fail_silently = False
            )
            msg='your password is sand to your mail check it now'
        except:
            msg = 'enter registered email'
     return render(request, 'common/seller_forgot.html', {'msg': msg})

def cust_forgot(request):
    msg =''
    if request.method=='POST':
        entered_email = request.POST['forget_mail']
        try:
            check=Customer.objects.get(e_mail = entered_email)
            password=check.password
            send_mail(
                'your password is',
                password,
                settings.EMAIL_HOST_USER,
                [entered_email],
                fail_silently = False
            )
            msg='your password is sand to your mail check it now'
        except:
            msg = 'enter registered email'
    return render(request, 'common/cust_forgot.html', {'msg': msg})

sample/furniture/common/templates/common/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        nav {


            display: flex;
            position: sticky;
            top: 0;
            z-index: 2;
            width: 100%;
            height: 80px;
            color: #fff;
            box-shadow: 2px 2px 5px #888888;
            background-color: lightblue;
        }

        nav ul {
            margin: 0;
            padding: 0;
            list-style: none;
            display: flex;
            margin-top: 20px;
            font-family: 'Kaushan Script', cursive;
            font-family: 'Libre Baskerville', serif;
            font-family: 'Poppins', sans-serif;
            /* justify-content: space-between; */
        }

        nav li {
            padding: 1rem;

        }

        nav a {
            color: white;
            text-decoration: none;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 19px;
            font-weight: 100px;
        }

        nav a:hover {
            color: #111110;
        }

        nav img {
            width: 20px;
            height: 30px;
        }

        input {
            margin-left: 80px;
            width: 400px;
            height: 40px;
            margin-top: 20px;

            border-radius: 8px;

        }

        .left {
            background-color: transparent;
            width: 30%;
            display: flex;
            justify-content: center;
            font-family: Arial, Helvetica, sans-serif;
            align-items: center;
            color: black;


        }
/* 
        #icon {
            width: 50px;
            height: 50px;
        } */

        .left ul {
            margin-top: 7px;
            /* margin-left: 60px; */
            color: black;
        }
       
        #name{
         margin-right: 280px;
        }
        .center {
            display: flex;
            background-color: transparent;
            width: 50%;

        }

        #input {
            margin-right: 50px;
        }

        .right {
            background-color: transparent;
            color: black;
            width: 20%;
            display: flex;
            flex-direction: row;
            justify-content: space-around;
            align-items: center;
            font-family: Arial, Helvetica, sans-serif;
        }

        .right button {

            width: 80px;
            border-radius: 7px;
            height: 30px;
            font-size: 13px;
            background-color: rgb(29, 28, 28);
            color: white;
        }

        .right #profile img {
            /* background-color: #f1c40f; */
            border-radius: 50px;
            width: 50px;
            height: 50px;
        }

        /* ////////////////////////////////content starting \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
        .container {
            /* background-color: rgb(101, 173, 101); */
            width: 90%;
            height: 500px;
            display: flex;
            margin-left: 65px;
            margin-top: 30px;
        }

        .left_about {
            /* background-color: lightcoral; */
            width: 20%;
            border-radius: 0% 100% 0% 100% / 100% 56% 44% 0%;
        }

        .left_about h3 {
            font-family: Arial, Helvetica, sans-serif;
            margin-top: 130%;
            margin-left: 25px;
            font-size: 35px;
        }

        .left_about p {
            padding-left: 20px;
            font-size: 24px;
            font-family: Arial, Helvetica, sans-serif;

        }

        .right_about {
            width: 90%;
            background-color: rgb(224, 224, 46);
            background: url("/static/images/about8.jpg");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            border-radius: 0% 100% 0% 100% / 43% 0% 100% 57%;
            border-bottom-right-radius: 8px;
            border-top-right-radius: 8px;
        }

        .container2 {
            /* background-color: rgb(157, 162, 194); */
            width: 90%;
            height: 400px;
            /* display: flex; */
            margin-left: 65px;
        }

        .container2 p {
            padding-left: 20px;
            font-size: 19px;
            font-family: Arial, Helvetica, sans-serif;

        }

        #p1 {
            font-size: 19px;
            margin-left: 370px;
        }

        #p2 {
            font-size: 19px;
            margin-left: 250px;
        }

        #p3 {
            font-size: 22px;
            margin-left: 40px;
        }
    </style>
</head>

<body>
    <nav>

        <div class="left">
            <div class="left_sub">
                <a href="http://127.0.0.1:8000/common/home"><h2 id="name">ΞLIΓΞ</h2></a>
            </div>
            <div class="left_sub">
                
            </div>
        </div>
        <div class="center">
            <input type="search" id="input" placeholder="Search......">
        </div>
        <div class="right">
            <div class="box"><a href="http://127.0.0.1:8000/customer/help">Help</a></div>
            <!-- <div id="profile">
                <a href="{% url 'customer:account' %}"><img src="{{user.image.url}}"></a>
            </div> -->
        </div>
    </nav>




    <div class="container">
        <div class="left_about">
            <p style="margin-left: 20px; margin-top: 20px; font-size: 25px;">ΞLIΓΞ</p>
            <h3>About Us</h3>
            <hr>
            <p><b> Welcome to Elite...!</b></p>
        </div>
        <div class="right_about"></div>

    </div>
    <div class="container2">
        <p id="p1"> Finally your go-to destination for stylish and affordable furniture.</p>
        <p> We're a family-owned business founded by a team of passionate designers and furniture experts who believe
            that everyone should have access to beautiful,<br> high-quality furnishings.

            Our mission is simple: to provide our customers with a curated selection of furniture that meets their
            unique needs and preferences.<br>Whether you're furnishing a cozy apartment or a spacious home, we have a
            wide range of styles and designs to choose from, including mid-century modern,<br> contemporary, and rustic.

            At Elite, we're committed to providing exceptional customer service.<br>
        <p id="p2"> Our team is dedicated to helping you find the perfect furniture pieces for your home, and we're
            always available</p>
        <p> to answer any questions you may have. Plus, with fast and reliable shipping, easy returns, and a hassle-free
            checkout process, shopping with us is a breeze.

            We're passionate about design and believe that furniture should be both beautiful and functional. That's why
            we carefully curate our selection <br>to ensure that every piece we offer meets our high standards for
            quality and style.<br>

            <b> Thank you for choosing Elite as your trusted source for furniture. We look forward to helping you create
                the home of your dreams.</b>
        </p>
        <h2 style="text-align: center; font-family: Arial, Helvetica, sans-serif;">Vist Again</h2>
        <h3 style="text-align: center; word-spacing: 8px; font-family: Arial, Helvetica, sans-serif;">Love From ELITE
            GROUP</h3>
    </div>
</body>

</html>

sample/furniture/common/templates/common/cust_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <link rel="stylesheet" href="{% static 'css/cust_login.css' %}">
</head>

<body>
    <div class="container">
        <div class="sub">
            <div class="left">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1 id="h1">Login</h1>
                    <hr id="hr"><br><br>

                    <input type="mail" name="c_mail" placeholder="Email">
                    <br><br><br>
                    <input type="password" name="c_pass" placeholder="password*">
                    <br><br>
                    <button>Continue</button><span><a href="http://127.0.0.1:8000/common/cust_forgot"> Forgot Pssword?</a></span>
                    <br><br>
                    <p class="new">Don't have an account? <a href="http://127.0.0.1:8000/common/cust_reg">sign up
                            now</a></p><span>{{msg}}</span>
                </form>
            </div>
            <div class="right">
                <img src="{% static 'images/log.png' %}" alt="">
            </div>
        </div>
    </div>
</body>

</html>

sample/furniture/common/templates/common/cust_reg.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/cust_reg.css' %}">
</head>
<body>
    <div class="container">
        <div class="sub">
            <div class="left">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1 id="h1">Sign Up</h1><br><hr id="hr"><br>
                    
                    <input type="text" name="c_name" placeholder="name*">
                    <br><br>
                    <select  name="c_gender" id="option">Gender
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                        <option value="other">Other</option>
                    </select><br><br>
                    <input type="number" name="c_number" placeholder="number*">
                    <br><br>
                    <input type="email" name="c_mail" placeholder="email*">
                    <br><br>
                    <input type="address" name="c_address" placeholder="address*">
                    <br><br>
                     <input type="password" name="c_pass" placeholder="password*">
                    <br><br>
                    <input type="password" name="c_confirm pass" placeholder="confirm password*">
                    <br><br>
                    <input type="file" id="cust_img" name="c_image"><br><br>
                    <button type="submit"><p>Sign Up</p></button>
                    <br><br>
                    
                    <p class="new">already have an account?<a href="http://127.0.0.1:8000/common/cust_login">Login</a></p>
                </form>
            </div>
            <div class="right">
                <img src="{% static 'images/log.png' %}" alt="">
            </div>
        </div>
    </div>
</body>
</html>

sample/furniture/common/templates/common/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/common_home.css' %}">
    <style>
     
    </style>
</head>

<body>
   <div class="main_home">
    <nav>

        <div class="left"> 
            <div class="left_sub">
                <h2 style="margin-left: 90px;">ΞLIΓΞ</h2>
            </div>
            <div class="left_sub">
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="http://127.0.0.1:8000/common/about">About</a></li>
                    <li><a href="#">Services</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
        </div>
        <div class="center">
            <input type="search" id="input" placeholder="Search......">
        </div>
        <div class="right">
         <div class="box"><a href="http://127.0.0.1:8000/common/seller_reg">Become a seller</a></div>
         <div class="box"><a href="http://127.0.0.1:8000/common/cust_login"> <button type="submit">signUp</button></a></div>
        
        </div>
    </nav>
    <h1 id="h11" >Furnish your dream<br> With our furniture!</h1>

   </div>
    
    <div class="content">
        <div class="child">
            <p class="ads_p" >Sofa Collection</p><span style="color:white;font-size: 30px; font-family: Arial, Helvetica, sans-serif;  padding-left:330px;"><b>Starting From only </b></span>
            <br>
            <p style="color: rgb(243, 243, 8);font-size: 35px;  padding-left:530px;"><b>8599</b> </p>
        </div>
        <div class="child2">
            <p class="ads_p2"> Sale Off</p>
            <p style="color: rgb(243, 243, 8);font-size: 35px;  margin-left: 40px;"><b> Up to 50%</b></p>
            <p style="font-size: 40px;  margin-left: 45px; color: #fff; font-family: Arial, Helvetica, sans-serif;"><b> For Chairs</b></p>
        </div>
    </div>
    <div class="heading_txt">
        <p>NEW ARRIVALS</p>
    </div>
     <div class="products" >
      {% for i in data %}
      <div class="items" >
        <div class="sub">
          <a href="{% url 'common:prod_list' i.id %}"><img id="pro_img" src="{{i.pro_image.url}}" ></a>
           <b>{{i.pro_name}}</b><br>
          <span style="color: rgb(233, 113, 113);"><b>PRICE:</b> <b>{{i.pro_price}}</b> </span><br>
          <span><b>Rating:</b></span> 
         </div>
      </div>
        
        {% endfor %}
     </div>
    <div class="show_box">
        <a href="http://127.0.0.1:8000/common/cust_login"><button type="submit" id="show">Show More</button></a>
    </div>
    <div class="container">
        
        <section class="showD">
         <div class="leftt">
             <h1>Exotic minimal furniture</h1>
             <p>
                 choose from a wide range of well-crafted premium quality wooden furniture online
             </p>
             <button id="btn2">Explore</button>
         </div>
         <div class="right2">
             <img src="{% static 'images/chair14.png' %}" alt="" class="meanimg">
         </div>
        </section>
        <section class="showM">
         <div>
             <img src="{% static 'images/chair17.png' %}" alt="">
             <div class="info">
                 <h4>Bruna Cush</h4>
                 <b>$145.60</b>
             </div>
         </div>
         <div>
             <img src="{% static 'images/chair10.png' %}" alt="">
             <div class="info">
                 <h4>Drop Type</h4>
                 <b>$265.50</b>
             </div>
         </div>
         <div>
             <img src="{% static 'images/chair13.png' %}" alt="">
             <div class="info">
                 <h4>Backboard</h4>
                 <b>$160.00</b>
             </div>
         </div>
        </section>
     </div>
     <br><br>
     <!-- /////////////////////foooter \\\\\\\\\\\\\\\\\\\\\\\-->
     <div class="contanier_footer">
        <div class="container_sub">
            <div class="div_1">
               <h3>TOP CATEGORIES</h3>
               <li><a href="">Table</a> </li>
               <li><a href="">Chair</a></li>
               <li><a href="">Sofa</a></li>
               <li><a href="">Bed</a></li>
             </div>
             <div class="div_2">
                 <h3>HELP</h3>
                 <li><a href="">Delivery</a></li>
                 <li><a href="">Returns</a></li>
                 <li><a href="">Track an order</a></li>
                 <li><a href="">Contact us</a></li>
              </div>
              <div class="div_3">
                 <h3>ABOUT US</h3>
                 <li><a href="">Careers</a></li>
                 <li><a href="">Terms & Conditios</a></li>
                 <li><a href="">Privacy Policy</a></li>
                 <li><a href="">Responsibility</a></li>
              </div>
              <div class="div_4">
                 <h3>FEEDBACK</h3>
                 <li>Leave a feedback</li>
                 <input type="text" placeholder="Type something.....">
                <button type="submit" style="width: 60px; height: 33px; border-radius: 8px;">submit</button>

              </div>
        </div>
        <div class="container_sub2">
            <div class="d1">
                <h4>FIND A STORE</h4><br>
                <button type="submit">STORE LOCATOR</button><br><br>
                
            </div>
            <div class="d2">
                <h5>FOLLOW US</h5>
                <img src="{% static 'images/mainlogs (3).png' %}">
                <img src="{% static 'images/mainlogs (2).png' %}">
                <img src="{% static 'images/mainlogs (1).png' %}">
                <img src="{% static 'images/youtube.png' %}">
            </div>
            <div class="d3">
                <h5>NEWS LETTER SUBSCRIPTION</h5>
                <p>Receive product news and upadtes in your mail</p>
                <input type="text" placeholder="Enter your mail">
                <button type="submit" style="width: 60px; height: 33px; border-radius: 8px;">submit</button>
                
            </div>
        </div>
    </div>
</body>

</html>

sample/furniture/common/templates/common/prod_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <style>
        .container{
            display: flex;
            width: 100%;
            height: 800px;
        }
        .sub{
            width: 1000px;
            display: flex;
            margin: auto;
            border-radius: 10px;
            box-shadow: 3px 3px 6px #888888;
        }
        .sub .left{
            width: 40%;
            height: 450px;
            border-top-left-radius: 10px;
            border-bottom-left-radius: 10px;
        }
       
        #pic{
            margin-top: 15px;
            margin-left: 30px;
            width: 85%;
            height: 420px;
            border-radius: 10px;
            box-shadow: 3px 3px 6px #888888;
        }
       /* #pic:hover{
           
        } */
        .sub .right{
            width: 60%;
            border-bottom-right-radius: 10px;
            border-top-right-radius: 10px;

        }
        .head{
            font-family: Arial, Helvetica, sans-serif;
            text-align: center;
        }
        #hrr{
            width: 180px;
        }
        .descrition{
            font-family: Arial, Helvetica, sans-serif;
            text-align: center;
        }
        #QTY{
            width: 50px;
            margin-left:45px;
            height: 35px;
            border-radius: 5px;
        }
        #h3{
            margin-left: 45px;
        }
        #btn1{
            width: 110px;
            height: 40px;
            background-color:white;
            color: black;
            margin-left: 20px;
            border-radius: 5px;
        }
        #btn1:hover{
            background-color: black;
            color: white;
        }

        #wish{
            text-decoration: none;
            color: black;
            font-family: Arial, Helvetica, sans-serif;
            margin-top: 30px;
            margin-left: 50px;
            padding-top: 30px;
        }
        #home-btn{
            width: 190px;
            height: 25px;
            background-color:white;
            color: black;
            margin-top: 30px;
            margin-left: 50px;
            border-radius: 8px;
            
        }
       

        #home-btn:hover{
            box-shadow: 3px 3px 6px #888888;
            background-color: black;
            color: white;
            font-weight: 300;
            
        }
       
    </style>
</head>
<body>
    <div class="container">
        <div class="sub">
            <div class="left">
                <img id="pic" src="{{data.pro_image.url}}">
            </div>
            <div class="right"> 
                  <div class="head">
                    <h1>{{data.pro_name}}</h1>
                    <hr id="hrr">
                  </div>
                  <div class="descrition">
                  <p>{{data.pro_description}}</p>
                  </div><br>
                 
                  <h3 id="h3"> <span><b>$</b></span>{{data.pro_price}}</h3>
                  <div class="qty">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="number" id="QTY" min="1" name="qty" placeholder="QTY">
                        <a href="http://127.0.0.1:8000/common/cust_login"><button id="btn1" type="submit">ADD TO CART</button></a>
                    
                  </div><br><br>
                 
                  <a href="" id="wish">Add to wishlist</a><i class='bx bx-heart'></i>
                  
                </form><br><br>
                <a href="{% url 'common:home' %}"><button id="home-btn" type="submit">Home</button></a>

            </div>
        </div>
    </div>
</body>
</html>