sample/furniture/common/urls.py
from django.urls import path
from .import views
app_name = 'common'
urlpatterns=[
     path('home',views.home, name="home"),
     path('cust_reg',views.cust_reg, name="cust_reg"),
     path('seller_reg',views.seller_reg, name="seller_reg"),
     path('cust_login',views.cust_login, name="cust_login"),
     path('seller_login',views.seller_login, name="seller_login"),
     path('seller_forgot',views.seller_forgot, name="seller_forgot"),
     path('cust_forgot',views.cust_forgot, name="cust_forgot"),
     path('prod_list/<int:id>',views.prod_list, name="prod_list"),
     path('about',views.abuot, name="about"),

]

sample/furniture/ecom_admin/urls.py
from django.urls import path
from .import views
app_name = 'ecom_admin'
urlpatterns=[
     path('home',views.home, name="home"),
     path('master',views.master, name="master"),
     path('profile',views.profile, name="profile"),
     path('seller_list',views.seller_list, name="seller_list"),
     path('customer_list',views.customer_list, name="customer_list"),
     path('approve_seller',views.approve_seller, name="approve_seller"),
     path('category',views.category, name="category"),
     path('approve_btn/<int:seller_id>', views.approve, name = 'approve_btn'),
     path('reject_btn/<int:seller_id>', views.reject, name= 'reject_btn')

]  

sample/furniture/furniture/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('customer/', include('customer.urls')),
    path('seller/', include('seller.urls'))
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sample/furniture/ecom_admin/models.py
from django.db import models

# Create your models here.
class Appadmin(models.Model):
    A_username=models.CharField(max_length=100)
    A_pssword=models.CharField(max_length=50)

    class Meta:
        db_table ='app_admin'

class Category(models.Model):
    category_name=models.CharField(max_length=100)
    description=models.CharField(max_length=300)
    image=models.ImageField(upload_to='category/')

    class Meta:
        db_table = 'category'

sample/furniture/ecom_admin/views.py
from django.shortcuts import render,redirect
from common.models import Customer, Seller

from django.core.mail import send_mail
from django.conf import settings
from django.http import JsonResponse
import random
from customer.models import CustomCart

from ecom_admin.models import Category

# Create your views here.
def home(request):
    total_seller = Seller.objects.all()
    total_customer = Customer.objects.all()
    total_order = CustomCart.objects.all()
    
    context = {
        'seller_count': total_seller.count(),
        'customer_count': total_customer.count(),
        'order_count':total_order.count(),
        'seller':total_seller,
        'customer': total_customer
    }
   
    return render(request, 'ecom_admin/home.html',context)

def master(request):
    return render(request, 'ecom_admin/master.html')

def profile(request):
    return render(request, 'ecom_admin/profile.html')

def seller_list(request):
    all_seller=Seller.objects.all()

    return render(request, 'ecom_admin/seller_list.html',{'data':all_seller})

def customer_list(request):
    all_cust=Customer.objects.all()
    
    return render(request, 'ecom_admin/customer_list.html',{'data':all_cust})

def approve_seller(request):
    seller= Seller.objects.filter(status = 'pending..')
    print(seller)
    return render(request, 'ecom_admin/approve_seller.html',{'data':seller})

def category(request):
    all_cat=Category.objects.all()
    if request.method == 'POST':
        category=request.POST['a_category']
        category_description=request.POST['a_description']
        try:
            category_image=request.FILES['cate_image']
        except:
            category_image=None
        new_category = Category(
            category_name=category,
            description=category_description,
            image=category_image
        )
        new_category.save()

        return redirect('ecom_admin:category')


    return render(request, 'ecom_admin/category.html',{'data':all_cat})

# \\\\\\\\\\\\\\APPROVE THE SELLER///////////

def approve(request,seller_id):
   
    try:
        change = Seller.objects.get(id=seller_id)

        print("STATUS CHANGED")
        seller_name= change.name
        mail = change.e_mail
        username = random.randint(1111,9999)
        password = '@' + seller_name.lower() + str(username)
        message = 'Mr/Mrs' + str(seller_name) + 'welcome to our shop, your username is : ' + str(username) + ' and your password is :' + str(password)
    
        send_mail(
            'Congradualations',
            message,
            settings.EMAIL_HOST_USER,
            [mail],
            fail_silently = False

        )
        print(mail,username,password)
        change.status = 'approved'
        change.username = username
        change.password = password
        change.save()
        
    except:
        print('500 ERROR') 
   
    return redirect('ecom_admin:approve_seller')       

def reject(request,seller_id):
    seller = Seller.objects.get(id =seller_id)
    name = seller.name
    mail = seller.e_mail 

    message = 'Mr/Mrs' + name + 'sorry for the in convenience you are no eligible for our terms and conditions ELITE FURNISHING'
    send_mail(
        'REJECTED',
        message,
        settings.EMAIL_HOST_USER,
        [mail],
        fail_silently = False
    )
    seller.save()

    return redirect('ecom_admin:approve_seller')  


    

sample/furniture/ecom_admin/templates/ecom_admin/approve_seller.html
{% extends "ecom_admin/master.html" %}
{% load static %}
{% block title %}approve seller{% endblock %}
{% block head %} <link rel="stylesheet" href="{% static 'css/approve_seller.css' %}">{% endblock %}
   
  {% block body %}

    <h2>APPROVE SELLER</h2>
    <div class="container">

        <table>
            <thead>
                <tr>
                    <th>NO</th>
                    <th>SELLER NAME</th>
                    <th>COMPANY NAME</th>
                    <th>PHONE</th>
                    <th>E-MAIL</th>
                    <th>APPROVE</th>
                    <th>REJECT</th>
                </tr>
            </thead>
            <tbody>
                {% for i in data %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{i.name}}</td>
                    <td>{{i.company_name}}</td>
                    <td>{{i.phone}}</td>
                    <td>{{i.e_mail}}</td>
                    <td ><a href="{% url 'ecom_admin:approve_btn' i.id %}"><button id="btn" type="submit">Approve</button></td></a> 
                    <td ><a href="{% url 'ecom_admin:reject_btn' i.id %}"><button id="btn2" type="submit">Reject</button></td></a> 
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endblock %}

sample/furniture/ecom_admin/templates/ecom_admin/category.html
{% extends "ecom_admin/master.html" %}
{% load static %}
{% block title %}category{% endblock %}
{% block head %}<link rel="stylesheet" href="{% static 'css/category.css' %}">
<script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>{% endblock %}

{% block body %}
    <h2>CATEGORY LIST</h2>
    <div class="btn-div">
        <div class="button">
            <button id="btn">Add category</button>
        </div>
    </div>
    <div style="display: none;" id="box-add">
        <div class="add"  >
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <br>
                <label for="">category-name</label><br>
                <input type="text" name="a_category"><br><br>
                <label for="">Description</label><br>
                <textarea name="a_description" id="" cols="40" rows="12"></textarea><br><br>
                <label for="" id="">Image</label>
                <input type="file" name="cate_image">
                <button id="btn2" type="submit">Add</button>
                <button id="btn3" type="submit">close</button>
               
            </form>
          
        </div>
    </div>
   <div class="container">
    <table>
        <thead>
            <tr>
                <th>CART_ID</th>
                <th>CATEGORY<br>NAME</th>
                <th>DESCRIPTION</th>
                <th>IMAGE</th>
            </tr>
        </thead>
        <tbody>
            {% for i in data %}
            <tr> 
                <td>{{ forloop.counter }}</td>
                <td>{{i.category_name}}</td>
                <td>{{i.description}}</td>
                <td><img id="category_image" src="{{i.image.url}}" alt=""></td>

                
            </tr>
            {% endfor %}
        </tbody>
    </table>
   </div>

   <script>
    $(document).ready(function(){
        $('#btn').click(function(){
            $('#box-add').css('display','block');  
        })

        $('#btn3').click(function(){
            $('#box-add').css('display','none');
        })
    })
</script>
{% endblock %}

sample/furniture/ecom_admin/templates/ecom_admin/customer_list.html
{% extends "ecom_admin/master.html" %}
{% load static %}
{% block title %}customer list{% endblock %}
{% block head %}<link rel="stylesheet" href="{% static 'css/customer_list.css' %}">{% endblock %}


{% block body %}
    <h2>CUSTOMERS</h2>
    <div class="container">
        <table>
            <thead>
                <tr>
                    <th>S NO</th>
                    <th>NAME</th>
                    <th>GENDER</th>
                    <th>ADDRESS</th>
                    <th>PHONE</th>
                    <th>E-MAIL</th>
                    <th>IMAGE</th>
                </tr>
            </thead>
            <tbody>
                {% for i in data %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{i.name}}</td>
                    <td>{{i.gender}}</td>
                    <td>{{i.address}}</td>
                    <td>{{i.phone}}</td>
                    <td>{{i.e_mail}}</td>
                    <td><img id="customer_img" src="{{i.image.url}}" ></td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

sample/furniture/ecom_admin/templates/ecom_admin/home.html
{% extends "ecom_admin/master.html" %}
{% load static %}
{% block title %}home{% endblock %}
{% block head %} <link rel="stylesheet" href="{% static 'css/admin_home.css' %}">{% endblock %}
   
  {% block body %}
 

    <div class="content">
      <div class="cards">
        <div class="card">
          <div class="box">
            <h1>{{customer_count}}</h1>
            <h3>Total customers</h3>
          </div>
          <div class="icon-case">
            <img src="{% static 'images/customer.png' %}" alt="">
          </div>
        </div>
        <div class="card">
          <div class="box">
            <h1>{{seller_count}}</h1>
            <h3>Total sellers</h3>
          </div>
          <div class="icon-case">
            <img src="{% static 'images/seller.png' %}" alt="">
          </div>
        </div>
        <div class="card">
          <div class="box">
            <h1>{{order_count}}</h1>
            <h3>Total orders</h3>
          </div>
          <div class="icon-case">
            <img src="{% static 'images/products.png' %}" alt="">
          </div>
        </div>
        <div class="card">
          <div class="box">
            <h1>2194</h1>
            <h3>income</h3>
          </div>
          <div class="icon-case">
            <img src="{% static 'images/wallet.png' %}" alt="">
          </div>
        </div>
      </div>
      <div class="content-2">
        <div class="recent-paymet">
          <div class="title">
            <h2>New Sellers</h2>
            <a href="{% url 'ecom_admin:seller_list' %}" class="btn">View All</a>
          </div>
          <table>
            <tr>
              <th>No</th>
              <th>Name</th>
              <th>Company Name</th>
              <th>Image</th>
            </tr>
            {% for i in seller %}
            <tr>
              <td>{{forloop.counter}}</td>
              <td>{{i.name}}</td>
              <td>{{i.company_name}}</td>
              <td><img id="seller_image" src="{{i.image.url}}" ></td>
            </tr>

            {% endfor %}
            
          </table>
        </div>
        <div class="new-customer">
          <div class="title">
            <h2>New Customers</h2>
            <a href="{% url 'ecom_admin:customer_list' %}" class="btn">View All</a>
          </div>
          <table>
            <tr>
              <th>NO</th>
              <th>Name</th>
              <th>image</th>
            </tr>
            {% for i in customer %}
            <tr>
              <td>{{forloop.counter}}</td>
              <td>{{i.name}}</td>
              <td><img id="customer_image" src="{{i.image.url}}" ></td>
            </tr>
            {% endfor %}
           
          </table>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

sample/furniture/ecom_admin/templates/ecom_admin/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'poppins', sans-serif;
        }

        body {
            min-height: 100vh;

        }

        a {
            text-decoration: none;
        }

        li {
            list-style: none;
        }

        h1,
        h2 {
            color: #444;
        }

        h3 {
            color: #999;
        }

        .btn {
            background: black;
            color: white;
            padding: 5px 10px;
            text-align: center;
            border-radius: 6px;
        }

        .btn:hover {
            color: black;
            background: rgb(250, 250, 215);
            padding: 3px 8px;
            border: 2px solid rgb(61, 27, 27);
        }

        .title {
            display: flex;
            align-items: center;
            justify-content: space-around;
            padding: 15px 10px;
            border-bottom: 2px solid #999;


        }

        table {
            padding: 10px;
        }

        th,
        td {
            text-align: center;
            padding: 8px;
        }

        .side-menu {
            position: fixed;
            background:#F7F4EB;
            width: 20vw;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
        }

        .side-menu .brand-name {
            height: 10vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .side-menu li {
            font-size: 23px;
            padding: 10px 40px;
            color: black;
            display: flex;
            align-items: center;

        }
        .side-menu li a{
            color: black;
        }

        .side-menu li:hover{
            background-color: rgb(116, 101, 101);
            color:#fff;
        }
        .side-menu li a:hover{
            color: #fff;
        }

        .container {
            position: absolute;
            right: 0;
            width: 80vw;
            height: 100vh;
            background: #f1f1f1;
        }

        .container .header {
            position: fixed;
            top: 0;
            right: 0;
            width: 80vw;
            height: 10vh;
            background: white;
            display: flex;
            align-items: center;
            justify-content: center;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            z-index: 1;
        }

        .container .header .nav {
            width: 90%;
            display: flex;
            align-items: center;

        }

        .container .header .nav .search {
            flex: 3;
            display: flex;
            justify-content: center;

        }

        .container .header .nav .search input[type=text] {
            border: none;
            background: #f1f1f1;
            padding: 10px;
            width: 50%;
        }

        .container .header .nav .search button {
            width: 40px;
            height: 40px;
            border: none;
            display: flex;
            align-items: center;
            justify-self: center;
            border-radius: 5px;


        }

        .container .header .nav .search button img {
            width: 30px;
            height: 30px;
        }

        .container .header .nav .user {
            flex: 1;
            display: flex;
            justify-content: space-between;
            align-items: center;

        }

        .container .header .nav .user img {
            width: 40px;
            height: 40px;
        }

        .container .header .nav .user .img-case {
            position: relative;
            width: 50px;
            height: 50px;
        }

        .container .header .nav .user .img-case img {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;

        }

     
    </style>
</head>

<body>
    <div class="side-menu">
        <div class="brand-name">
          <h1>ΞLIΓΞ</h1>
        </div>
        <ul>
          <li><img src="{% static 'images/dashboard.png' %}" ><span> <a href="{% url 'ecom_admin:home' %}"> Dashboard</a></span></li>
          <li><img src="{% static 'images/approve.png' %}" > <span><a href="{% url 'ecom_admin:approve_seller' %}" >Approve seller</a> </span> </li>
          <li><img src="{% static 'images/category.png' %}" > <span><a href="{% url 'ecom_admin:category' %}" >Category</a> </span></li>
          <li><img src="{% static 'images/customer.png' %}" > <span><a href="{% url 'ecom_admin:customer_list' %}" >Customer list</a></span> </li>
          <li><img src="{% static 'images/seller.png' %}" > <span><a href="{% url 'ecom_admin:seller_list' %}" >Seller list</a> </span> </li>
          <li><img src="{% static 'images/settings.png' %}" > <span><a href=""> Settings</a></span> </li>
    
        </ul>
      </div>
      <div class="container">
        <div class="header">
          <div class="nav">
            <div class="search">
              <input type="text" placeholder="search">
              <button type="submit"><img src="{% static 'images/search.png' %}" alt=""></button>
            </div>
            <div class="user">
              <a href="{% url 'ecom_admin:approve_seller' %}" class="btn">Add new</a>
              <img src="{% static 'images/notification.png' %}" alt="">
              <div class="img-case">
                <a href="{% url 'ecom_admin:profile' %}"><img src="{% static 'images/user.png' %}" alt=""></a>
              </div>
            </div>
          </div>
        </div>
        {% block body %}{% endblock %}

sample/furniture/ecom_admin/templates/ecom_admin/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

sample/furniture/ecom_admin/templates/ecom_admin/seller_list.html
{% extends "ecom_admin/master.html" %}
{% load static %}
{% block title %}seller list{% endblock %}
{% block head %} <link rel="stylesheet" href="{% static 'css/seller_list.css' %}">{% endblock %}
   
  {% block body %}

    <h2>SELLERS</h2>
    <div class="container">
        <table>
            <thead>
                <tr>
                    <th>S NO</th>
                    <th>NAME</th>
                    <th>GENDER</th>
                    <th>COMPANY NAME</th>
                    <th>PHONE</th>
                    <th>E-MAIL</th>
                    <th>BANK-AC-NO</th>
                    <th>IMAGE</th>
                </tr>
            </thead>
            <tbody>
                {% for i in data %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{i.name}}</td>
                    <td>{{i.gender}}</td>
                    <td>{{i.company_name}}</td>
                    <td>{{i.phone}}</td>
                    <td>{{i.e_mail}}</td>
                    <td>{{i.accNo}}</td>
                    <td><img id="seller_img"  src="{{i.image.url}}"></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% endblock %}