sample/furniture/common/urls.py
from django.urls import path
from .import views
app_name = 'common'
urlpatterns=[
     path('home',views.home, name="home"),
     path('cust_reg',views.cust_reg, name="cust_reg"),
     path('seller_reg',views.seller_reg, name="seller_reg"),
     path('cust_login',views.cust_login, name="cust_login"),
     path('seller_login',views.seller_login, name="seller_login"),
     path('seller_forgot',views.seller_forgot, name="seller_forgot"),
     path('cust_forgot',views.cust_forgot, name="cust_forgot"),
     path('prod_list/<int:id>',views.prod_list, name="prod_list"),
     path('about',views.abuot, name="about"),

]

sample/furniture/customer/urls.py
from django.urls import path
from .import views
app_name = 'customer'
urlpatterns=[
     path('home',views.home, name="home"),
     path('help',views.help, name="help"),
     path('cart',views.cart, name="cart"),
     path('product_dtls/<int:id>',views.product_dtls, name="product_dtls"),
     path('product/<int:id>',views.product, name="product"),
     path('master',views.master, name="master"),
     path('myorders',views.myorders, name="myorders"),
     path('remove/<int:id>', views.remove, name='remove'),
     path('cust_logout',views.cust_logout, name='cust_logout'),
     path('account',views.account, name='account'),
     path('about',views.about, name='about'),
     path('checkout',views.checkout, name='checkout'),
     path('payment',views.payment, name='payment'),
     path('result',views.result, name='result'),


]     

sample/furniture/furniture/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('customer/', include('customer.urls')),
    path('seller/', include('seller.urls'))
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sample/furniture/customer/models.py
from django.db import models
from common.models import Customer

from seller.models import Product

# Create your models here.
class CustomCart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    class Meta:
        db_table = "cart"

sample/furniture/customer/views.py
from django.db.models.functions import Random
from django.shortcuts import redirect, render
from common.models import Customer
from customer.models import CustomCart
from django.db.models import F
from random import sample

from seller.models import Product

# Create your views here.
def home(request):
    customer=Customer.objects.get(id=request.session['Customer'])
    all_product = Product.objects.order_by(Random())
    setlimit = sample(list(all_product),12)
    context = {
        'data' : setlimit,
        'user':customer

    }
    return render(request, 'customer/home.html',context)

def cart(request):
    customer=Customer.objects.get(id=request.session['Customer'])

    cart_data = CustomCart.objects.filter(customer_id=request.session['Customer']).annotate(total=F('product__pro_price')*F('quantity'))
    grand_total = 0
  
    for i in cart_data:
        grand_total += i.total

    context = {
        'data': cart_data,
        'grand_total': grand_total,
        'user':customer
    }
    return render(request, 'customer/cart.html',context)

def product_dtls(request,id):
    view_product=Product.objects.get(id=id)

    if request.method == 'POST':
        prod_id=Product.objects.get(id=id)
        cust_id=Customer.objects.get(id = request.session['Customer'])
        qty=request.POST['qty']
        
        add_cart = CustomCart(
            product=prod_id,
            customer=cust_id,
            quantity=qty
        )
        add_cart.save()

    return render(request, 'customer/product_dtls.html',{'data':view_product})

def product(request,id):
    customer=Customer.objects.get(id=request.session['Customer'])
    
    fillter = Product.objects.filter(pro_category__id=id)

    return render(request, 'customer/product.html',{'data':fillter,'user':customer})

def master(request):
    customer=Customer.objects.get(id=request.session['Customer'])
    return render(request, 'customer/master.html',{'user':customer})

def myorders(request):
    return render(request, 'customer/myorders.html')

def checkout(request):
    return render(request, 'customer/checkout.html')

def payment(request):
    return render(request, 'customer/payment.html')

def result(request):
    return render(request, 'customer/result.html')

def about(request):
    customer=Customer.objects.get(id=request.session['Customer'])

    return render(request, 'customer/about.html',{'user':customer})

def account(request):
    customer=Customer.objects.get(id=request.session['Customer'])
    if request.method == 'POST':
        up_name = request.POST['ed_name']
        up_phone = request.POST['ed_phone']
        up_email = request.POST['ed_email']
        up_gender = request.POST['ed_gender']
        up_address = request.POST['ed_address']

        edit_customer = Customer.objects.filter(id=request.session['Customer'])

        if (up_name != ''):
            edit_customer.update(name=up_name)
        else:
            print('else')
        if (up_phone != ''):
            edit_customer.update(phone=up_phone)
        else:
            print('else')
         
        if (up_email != ''):
            edit_customer.update(e_mail=up_email)
        else:
            print('else')
        if (up_gender != ''):
            edit_customer.update(gender=up_gender)
        else:
            print('else')
        if (up_address != ''):
            edit_customer.update(address=up_address)
        else:
            print('else')
        try:
            up_image = request.FILES['ed_image']
            customer.image = up_image
            customer.save()
        except:
            up_image = None
    return render(request, 'customer/account.html',{'user':customer})


def help(request):
    customer=Customer.objects.get(id=request.session['Customer'])
    
    return render(request, 'customer/help.html',{'user':customer})

def remove(request, id):
    remove_data = CustomCart.objects.filter(product_id=id)
    remove_data.delete()
    return redirect('customer:cart')

def cust_logout(request):
    del request.session['Customer']
    request.session.flush()
    return redirect('common:home')




   

sample/furniture/customer/templates/customer/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        nav {


            display: flex;
            position: sticky;
            top: 0;
            z-index: 2;
            width: 100%;
            height: 80px;
            color: #fff;
            box-shadow: 2px 2px 5px #888888;
            background-color: lightblue;
        }

        nav ul {
            margin: 0;
            padding: 0;
            list-style: none;
            display: flex;
            margin-top: 20px;
            font-family: 'Kaushan Script', cursive;
            font-family: 'Libre Baskerville', serif;
            font-family: 'Poppins', sans-serif;
            /* justify-content: space-between; */
        }

        nav li {
            padding: 1rem;

        }

        nav a {
            color: white;
            text-decoration: none;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 19px;
            font-weight: 100px;
        }

        nav a:hover {
            color: #111110;
        }

        nav img {
            width: 20px;
            height: 30px;
        }

        input {
            margin-left: 80px;
            width: 400px;
            height: 40px;
            margin-top: 20px;

            border-radius: 8px;

        }

        .left {
            background-color: transparent;
            width: 30%;
            display: flex;
            justify-content: center;
            font-family: Arial, Helvetica, sans-serif;
            align-items: center;
            color: black;


        }
/* 
        #icon {
            width: 50px;
            height: 50px;
        } */

        .left ul {
            margin-top: 7px;
            /* margin-left: 60px; */
            color: black;
        }
       
        #name{
         margin-right: 280px;
        }
        .center {
            display: flex;
            background-color: transparent;
            width: 50%;

        }

        #input {
            margin-right: 50px;
        }

        .right {
            background-color: transparent;
            color: black;
            width: 20%;
            display: flex;
            flex-direction: row;
            justify-content: space-around;
            align-items: center;
            font-family: Arial, Helvetica, sans-serif;
        }

        .right button {

            width: 80px;
            border-radius: 7px;
            height: 30px;
            font-size: 13px;
            background-color: rgb(29, 28, 28);
            color: white;
        }

        .right #profile img {
            /* background-color: #f1c40f; */
            border-radius: 50px;
            width: 50px;
            height: 50px;
        }

        /* ////////////////////////////////content starting \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
        .container {
            /* background-color: rgb(101, 173, 101); */
            width: 90%;
            height: 500px;
            display: flex;
            margin-left: 65px;
            margin-top: 30px;
        }

        .left_about {
            /* background-color: lightcoral; */
            width: 20%;
            border-radius: 0% 100% 0% 100% / 100% 56% 44% 0%;
        }

        .left_about h3 {
            font-family: Arial, Helvetica, sans-serif;
            margin-top: 130%;
            margin-left: 25px;
            font-size: 35px;
        }

        .left_about p {
            padding-left: 20px;
            font-size: 24px;
            font-family: Arial, Helvetica, sans-serif;

        }

        .right_about {
            width: 90%;
            background-color: rgb(224, 224, 46);
            background: url("/static/images/about8.jpg");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            border-radius: 0% 100% 0% 100% / 43% 0% 100% 57%;
            border-bottom-right-radius: 8px;
            border-top-right-radius: 8px;
        }

        .container2 {
            /* background-color: rgb(157, 162, 194); */
            width: 90%;
            height: 400px;
            /* display: flex; */
            margin-left: 65px;
        }

        .container2 p {
            padding-left: 20px;
            font-size: 19px;
            font-family: Arial, Helvetica, sans-serif;

        }

        #p1 {
            font-size: 19px;
            margin-left: 370px;
        }

        #p2 {
            font-size: 19px;
            margin-left: 250px;
        }

        #p3 {
            font-size: 22px;
            margin-left: 40px;
        }
    </style>
</head>

<body>
    <nav>

        <div class="left">
            <div class="left_sub">
                <a href="http://127.0.0.1:8000/customer/home"><h2 id="name">ΞLIΓΞ</h2></a>
            </div>
            <div class="left_sub">
                
            </div>
        </div>
        <div class="center">
            <input type="search" id="input" placeholder="Search......">
        </div>
        <div class="right">
            <div class="box"><a href="http://127.0.0.1:8000/customer/help">Help</a></div>
            <div id="profile">
                <a href="{% url 'customer:account' %}"><img src="{{user.image.url}}"></a>
            </div>
        </div>
    </nav>




    <div class="container">
        <div class="left_about">
            <p style="margin-left: 20px; margin-top: 20px; font-size: 25px;">ΞLIΓΞ</p>
            <h3>About Us</h3>
            <hr>
            <p><b> Welcome to Elite...!</b></p>
        </div>
        <div class="right_about"></div>

    </div>
    <div class="container2">
        <p id="p1"> Finally your go-to destination for stylish and affordable furniture.</p>
        <p> We're a family-owned business founded by a team of passionate designers and furniture experts who believe
            that everyone should have access to beautiful,<br> high-quality furnishings.

            Our mission is simple: to provide our customers with a curated selection of furniture that meets their
            unique needs and preferences.<br>Whether you're furnishing a cozy apartment or a spacious home, we have a
            wide range of styles and designs to choose from, including mid-century modern,<br> contemporary, and rustic.

            At Elite, we're committed to providing exceptional customer service.<br>
        <p id="p2"> Our team is dedicated to helping you find the perfect furniture pieces for your home, and we're
            always available</p>
        <p> to answer any questions you may have. Plus, with fast and reliable shipping, easy returns, and a hassle-free
            checkout process, shopping with us is a breeze.

            We're passionate about design and believe that furniture should be both beautiful and functional. That's why
            we carefully curate our selection <br>to ensure that every piece we offer meets our high standards for
            quality and style.<br>

            <b> Thank you for choosing Elite as your trusted source for furniture. We look forward to helping you create
                the home of your dreams.</b>
        </p>
        <h2 style="text-align: center; font-family: Arial, Helvetica, sans-serif;">Vist Again</h2>
        <h3 style="text-align: center; word-spacing: 8px; font-family: Arial, Helvetica, sans-serif;">Love From ELITE
            GROUP</h3>
    </div>
</body>

</html>

sample/furniture/customer/templates/customer/account.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

</head>
<body>
    <!-- //////////nav starting\\\\\\\\\\\\\\\ -->

    <nav>

        <div class="left_nav">
            <div class="left_sub">
                <a href="http://127.0.0.1:8000/customer/home"><h2 style="margin-right: 60px;">ΞLIΓΞ</h2></a>
            </div>
            <div class="left_sub">
                <ul>
                    <li><a href="#">About</a></li>
                    <li><a href="http://127.0.0.1:8000/customer/help"><span class="material-symbols-outlined">
                        Phone_In_Talk
                        </span></a></li>
                </ul>
            </div>
        </div>
        <div class="center">
            <input type="search" id="inputt" placeholder="Search......">
        </div>
        <div class="right_nav">
            <div class="box"><a href="{% url 'customer:cust_logout' %}"><span class="material-symbols-outlined">
                Logout
                </span></a></div>
            <div class="box"><a href="http://127.0.0.1:8000/customer/cart"><span class="material-symbols-outlined">
                shopping_cart_checkout
                </span></a></div>
            <div id="profile">
               <a href="{% url 'customer:account' %}"><img src="{{user.image.url}}" ></a> 
            </div>
        </div>
    </nav>

    <!-- //////////nav ending\\\\\\\\\\\\\\\ -->

    <div  class="links">
        <button id="update" type="submit">UPDATE</button>
        <a href="http://127.0.0.1:8000/customer/myorders"><button>MY ORDER</button></a>

    </div>
    
    <div class="container">
        <div class="sub">

            <div class="left">
                <div class="image">
                    <img id="imgg" src="{{user.image.url}}" alt="">
                </div>
            </div>
            <div class="right">
                <table>
                    <thead>
                        <tr>
                            <td>
                                <h1><i>{{user.name}}</i></h1><br>
                            </td>
                           
                        </tr>
                        <tr>
                            <td>
                                <h3><i>{{user.gender}}</i></h3>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h3><i>{{user.phone}}</i></h3>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h3><i>{{user.e_mail}}</i></h3>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h3><i>{{user.address}}</i></h3>
                            </td>
                        </tr>
                    </thead>
                </table>
            </div>
            <div id="update_div">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h2 style="text-align: center; color: #fff;">EDIT YOUR DETAILS</h2>
                    <br>
                    <input type="text" name="ed_name" placeholder=" Name">
                    <input type="mail" name="ed_email" placeholder="E-mail">
                    <select name="ed_gender" id="">
                        <option value="">gender</option>
                        <option value="male">male</option>
                        <option value="female">female</option>
                    </select>
                    <input type="number" name="ed_phone" placeholder="Mobile" min="0"><br><br><br>
                    <input type="Addreas" name="ed_address" placeholder="Address">
                    <input type="file" id="pro_img" name="ed_image"><br><br>
                    <button type="submit" id="sub_btn">SUBMIT</button>
                    <button type="submit" id="sub_btn2">CLOSE</button>

                </form>
            </div>

        </div>
    </div>

    <!-- ////////footer starting ////////////-->
    <div class="contanier_footer">
        <div class="container_sub">
            <div class="div_1">
                <h3>TOP CATEGORIES</h3>
                <li><a href="">Table</a> </li>
                <li><a href="">Chair</a></li>
                <li><a href="">Sofa</a></li>
                <li><a href="">Bed</a></li>
            </div>
            <div class="div_2">
                <h3>HELP</h3>
                <li><a href="">Delivery</a></li>
                <li><a href="">Returns</a></li>
                <li><a href="">Track an order</a></li>
                <li><a href="">Contact us</a></li>
            </div>
            <div class="div_3">
                <h3>ABOUT US</h3>
                <li><a href="">Careers</a></li>
                <li><a href="">Terms & Conditios</a></li>
                <li><a href="">Privacy Policy</a></li>
                <li><a href="">Responsibility</a></li>
            </div>
            <div class="div_4">
                <h3>FEEDBACK</h3>
                <li>Leave a feedback</li>
                <input type="text" placeholder="Type something.....">
            </div>
        </div>
        <div class="container_sub2">
            <div class="d1">
                <h4>FIND A STORE</h4>
                <button type="submit">STORE LOCATOR</button>
            </div>
            <div class="d2">
                <h5>FOLLOW US</h5>
                <img src="{% static 'images/mainlogs (3).png' %}">
                <img src="{% static 'images/mainlogs (2).png' %}">
                <img src="{% static 'images/mainlogs (1).png' %}">
                <img src="{% static 'images/youtube.png' %}">
            </div>
            <div class="d3">
                <h5>NEWS LETTER SUBSCRIPTION</h5>
                <p>Receive product news and upadtes in your mail</p>
                <input type="text" placeholder="Enter your mail">
            </div>
        </div>
    </div>
    <!-- ////////footer ending ////////////-->

    <script>
        $(document).ready(function () {
            $('#update').click(function () {
                $('#update_div').css('display', 'block');
            })

            $('#sub_btn2').click(function () {
                $('#update_div').css('display', 'none');
            })
        })
    </script>
</body>
</html>

sample/furniture/customer/templates/customer/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>checkout</h1>
</body>
</html>

sample/furniture/customer/templates/customer/home.html
{% extends "customer/master.html" %}
{% load static %}
{% block title %}home{% endblock %}
{% block head %} <link rel="stylesheet" href="{% static 'css/home.css' %}">{% endblock %}
   
  {% block body %}
  <div style="display: flex;
            justify-content: center;
            align-items: center;
            width: 100%;
            height: 50px;
            background-color: rgb(187, 206, 206);
            gap: 40px;" >
    <a href="{% url 'customer:product' 7 %}"><div class="sub-div">CHAIR</div></a>
    <a href="{% url 'customer:product' 8 %}"><div class="sub_div">TABLE</div></a>
    <a href="{% url 'customer:product' 9 %}"><div class="sub_div">SOFA</div></a>
    <a href="{% url 'customer:product' 10 %}"><div class="sub_div">BED</div></a>
  </div>
  <div class="main">
    <!-- <h1 id="h11">Design Your Home<br> With us</h1> -->

  </div>
  <br><br>
    <div class="products" >
      {% for i in data %}
      <div class="items" >
        <div class="sub">
          <a href="{% url 'customer:product_dtls' i.id %}"><img style="width: 260px; height:300px; " src="{{i.pro_image.url}}" ></a>
           <b>{{i.pro_name}}</b><br>
          <span style="color: rgb(231, 66, 66);"><b>₹ :</b> <b>{{i.pro_price}}</b> </span><br>
          <span><b>Rating:</b></span> 
         </div>
      </div>
        
        {% endfor %}
     </div>

     {% endblock %}

sample/furniture/customer/templates/customer/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    {% block head %}{% endblock %}
    
    <style>
        * {
            padding: 0;
            margin: 0;
            
        }

        a {
            text-decoration: none;
        }

        nav {


            display: flex;
            position: sticky;
            top: 0;
            z-index: 2;
            width: 100%;
            height: 80px;
            color: #fff;
            box-shadow: 2px 2px 5px #888888;
            background-color: rgb(84, 95, 97);
        }

        nav ul {
            margin: 0;
            padding: 0;
            list-style: none;
            display: flex;
            margin-top: 20px;
            font-family: 'Kaushan Script', cursive;
            font-family: 'Libre Baskerville', serif;
            font-family: 'Poppins', sans-serif;
            /* justify-content: space-between; */
        }

        nav li {
            padding: 1rem;

        }

        nav a {
            color: white;
            text-decoration: none;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 19px;
            font-weight: 100px;
        }

        nav a:hover {
            color: #111110;
        }

        nav img {
            width: 20px;
            height: 30px;
        }

        input {
            margin-left: 80px;
            width: 400px;
            height: 40px;
            margin-top: 20px;

            border-radius: 8px;

        }

        .left {
            background-color: transparent;
            width: 30%;
            display: flex;
            justify-content: center;
            font-family: Arial, Helvetica, sans-serif;
            align-items: center;
            color: black;


        }

        #icon {
            width: 50px;
            height: 50px;
        }

        .left ul {
            margin-top: 7px;
            /* margin-left: 60px; */
            color: black;
        }

        .center {
            display: flex;
            background-color: transparent;
            width: 50%;

        }

        #input {
            margin-right: 50px;
        }

        .right {
            background-color: transparent;
            color: black;
            width: 20%;
            display: flex;
            flex-direction: row;
            justify-content: space-around;
            align-items: center;
            font-family: Arial, Helvetica, sans-serif;
        }

        .right button {

            width: 80px;
            border-radius: 7px;
            height: 30px;
            font-size: 13px;
            background-color: rgb(29, 28, 28);
            color: white;
        }

        .right #profile img {
            /* background-color: #f1c40f; */
            border-radius: 50px;
            width: 50px;
            height: 50px;
        }

        /*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ footer starting ///////////////////////////////////////////////*/

        .contanier_footer {
            background-color: black;
            width: 100%;
            height: 390px;
        }

        .contanier_footer * li {
            list-style: none;
            padding: 10px;
            font-size: 17px;
        }

        .contanier_footer * li a {
            text-decoration: none;
            color: #fff;
        }

        .contanier_footer h3,
        h4,
        h5,
        p,
        li {
            color: #fff;
        }

        .contanier_footer .container_sub {
            display: grid;
            grid-template-columns: auto auto auto auto;
            text-align: center;
            font-family: cursive;
            padding-top: 30px;
        }

        .div_4 input {
            width: 170px;
            height: 25px;
            border-radius: 5px;
        }

        .container_sub2 {
            display: flex;
            margin-top: 20px;
            background-color: black;
            gap: 10px;
            text-align: center;
            align-items: center;
            font-family: cursive;
            height: 170px;
        }

        .container_sub2 .d1 {
            width: 40%;
        }

        .container_sub2 .d1 button {
            width: 200px;
            height: 35px;
            background-color: rgb(223, 223, 146);
            color: black;
            border-radius: 5px;
        }

        .container_sub2 .d2 {
            width: 20%;
        }

        .container_sub2 .d2 img {
            width: 30px;
            height: 30px;
        }

        .container_sub2 .d3 {
            width: 40%;
        }

        .container_sub2 .d3 input {
            width: 200px;
            height: 30px;
            border-radius: 5px;
        }
    </style>
</head>



<body>


    <nav>

        <div class="left">
            <div class="left_sub">
                <a href="http://127.0.0.1:8000/customer/home"><h2 style="margin-right: 120px;">ΞLIΓΞ</h2></a>
            </div>
            <div class="left_sub">
                <ul>
                    <li><a href="http://127.0.0.1:8000/customer/about">About</a></li>
                    <li><a href="http://127.0.0.1:8000/customer/help"><span class="material-symbols-outlined">
                        support_agent
                        </span></a></li>
                </ul>
            </div>
        </div>
        <div class="center">
            <input type="search" id="input" placeholder="Search......">
        </div>
        <div class="right">
            <div class="box"><a href="{% url 'customer:cust_logout' %}"><span class="material-symbols-outlined">
                Logout
                </span></a></div>
            <div class="box"><a href="http://127.0.0.1:8000/customer/cart"><span class="material-symbols-outlined">
                shopping_cart_checkout
                </span></a></div>
            <div id="profile">
               <a href="{% url 'customer:account' %}"><img src="{{user.image.url}}" ></a> 
            </div>
        </div>
    </nav>


    {% block body %}{% endblock %}


    <div class="contanier_footer">
        <div class="container_sub">
            <div class="div_1">
                <h3>TOP CATEGORIES</h3>
                <li><a href="">Table</a> </li>
                <li><a href="">Chair</a></li>
                <li><a href="">Sofa</a></li>
                <li><a href="">Bed</a></li>
            </div>
            <div class="div_2">
                <h3>HELP</h3>
                <li><a href="">Delivery</a></li>
                <li><a href="">Returns</a></li>
                <li><a href="">Track an order</a></li>
                <li><a href="">Contact us</a></li>
            </div>
            <div class="div_3">
                <h3>ABOUT US</h3>
                <li><a href="">Careers</a></li>
                <li><a href="">Terms & Conditios</a></li>
                <li><a href="">Privacy Policy</a></li>
                <li><a href="">Responsibility</a></li>
            </div>
            <div class="div_4">
                <h3>FEEDBACK</h3>
                <li>Leave a feedback</li>
                <input type="text" style="width: 160px; height: 30px;" placeholder="Type something.....">
                <button type="submit" style="width: 60px; height: 33px; border-radius: 8px; margin-right: 70px;">submit</button>

            </div>
        </div>
        <div class="container_sub2">
            <div class="d1">
                <h4>FIND A STORE</h4>
                <button type="submit">STORE LOCATOR</button>
            </div>
            <div class="d2">
                <h5>FOLLOW US</h5>
                <img src="{% static 'images/mainlogs (3).png' %}">
                <img src="{% static 'images/mainlogs (2).png' %}">
                <img src="{% static 'images/mainlogs (1).png' %}">
                <img src="{% static 'images/youtube.png' %}">
            </div>
            <div class="d3">
                <h5>NEWS LETTER SUBSCRIPTION</h5>
                <p>Receive product news and upadtes in your mail</p>
                <input style="margin-left: 80px;" type="text" placeholder="Enter your mail">
                <button type="submit" style="width: 60px; height: 33px; border-radius: 8px; margin-right: 70px;">submit</button>
            </div>
        </div>
    </div>
</body>

</html>